# Conclusion

From our study on tourism, we learned that climate, happiness, and economy are directly related to tourism. These are complex relationships across every country, but it is clear from our analysis that tourism has a positive impact on economy, and tourists flock to countries with less climate disasters and higher perceived happiness. Tourism is a worthwhile investment for a country. It was interesting to study multiple factors when it comes to tourism, not simply how much tourism occurs in each country. We enjoyed studying deeper and looking at impacts on society and climate. It was rewarding to see that most of our hypotheses were correct, and we enjoyed learning about the positives and negatives of tourism.

With only ten visuals, our study was limited. There were many relationships that we could have studied that were beyond the scope of this project. It was difficult to choose which variables to study, but we decided to cover a small portion of each area of interest, so that we could cover different aspects of tourism. Because of this, we were not able to dive deep into each subject, but we did enjoy learning a bit about each one. In the future, we would study more type of tourism, not simply inbound arrivals. We would like to analyze different types of travel (personal vs business), more on outbound travel, and more about the tourism industry itself (hotels, restaurants, airports, etc...). We would also like to look more into the effect of tourism on climate, as we were only able to study the impact of climate disasters on tourism. We would like to see whether tourism is a cause fo climate change as well.
