# Introduction

The objective of this project is to explore the intricate relationship between tourism and economic indicators and climate conditions. We begin the exploration by assessing the significance of tourism in each country by examining domestic, inbound and outbound tourism coupled with tourist expenditure for each of these categories. Once we understand trends in global tourism, our focus shifts to how tourism factors into global economies.

Tourism plays a pivotal role in many countries, especially in those with tropical climates. For example, in 2019, it was reported that tourism contributed to over 30% of the GDP for Macau, Maldives and Aruba. In studying how travel factors into GDP globally, we aim to identify seasonal and geographical trends. This includes the impact of significant events such as the COVID-19 pandemic, on the global travel economy. We also hope to discern emerging travel corridors resulting from re-opening borders or economic stimulation. Our investigation also extends to metrics such as employment, which are also markers of economic health for the tourism industry.

The surge of large climate events such as heat waves, floods and forest fires around the world, also prompts us to consider how tourism and climate are intertwined. In examining air travel alone, we can observe the carbon footprint of travel. We're also interested in understanding how natural disasters and evolving climate conditions may have affected popular tourist destinations.

Lastly, we are interested in examining concurrent trends in happiness and tourism across countries. Powered by the Gallup World Surveys, the data from the World Happiness Report contains metrics such as Social Support, Healthy Life, and Perceptions of Corruption to get a holistic view of population happiness in a given country. The dataset also maps the happiness metrics to GDP per capita, which we plan to leverage as well. By exploring this data, we hope to understand whether any of the factors influencing population happiness could also affect tourism levels. It's also possible that tourism levels impact over population happiness of a country, which makes this an interesting relationship to study. We hope to get a preliminary idea of whether population happiness and tourism could be intertwined in any way.

Our motivation for choosing this topic stems from our interest in exploring geography. The study of tourism metrics aligns well with geography, as we can easily identify regional differences and global, cyclical trends. The steep decline in travel during the years of the COVID-19 pandemic spurred our curiosity about the resurgence of the tourism. To this end, we want to understand whether economic and climate conditions are conducive to tourism and vice-versa.
